### ISSUE TITLE
Error in solar-bt-monitor.py?

### ISSUE THREAD

**Issue by iainjubb** [snichol67/solar-bt-monitor#1]
I've managed to get through all the install and whilst i havent connected it to my device yet (i'm not with my device), i get this error when trying to run?

pi@solar-monitor:~/solar-bt-monitor $ ./solar-bt-monitor.py
Traceback (most recent call last):
  File "/home/pi/solar-bt-monitor/./solar-bt-monitor.py", line 74, in <module>
    from prometheus_logger import prometheus_logger
  File "/home/pi/solar-bt-monitor/prometheus_logger.py", line 16, in <module>
    from prometheus_client import start_http_server, Gauge
ModuleNotFoundError: No module named 'prometheus_client'

Also I cant connect to 192.168.1.XXX:5000? (using my IP address). I can connect to :3000 and :9090

**Comment by snichol67** [comment]
It sounds like you don't have the prometheus python client installed.  I may have missed that step in the setup document.  Can you try running this on your raspberry pi:

`pip install prometheus-client `

Let me know the results and I can update the instructions!

**Comment by iainjubb** [comment]
I’ve pretty much got it all installed. Few issues along the way. I’ll document them and feed back. One of the main ones is that there is no longer the standard pi/raspberry login. It meant Prometheus didn’t work. Got that figured out and then few other things.

I’ve got data working however grafana doesn’t display it all. It’s also wrong and changes every 30s. So for example the number for battery % charge changes every cycle. I haven’t have chance to look at it just yet as only just got that bit working. Seems a mismatch between the grafana and the data source somehow.

The solar-by-monitor.py file running in the terminal is returning the right information every 30s.

On 4 Jan 2023, at 20:21, scott nichol ***@***.***> wrote:

﻿

It sounds like you don't have the prometheus python client installed. I may have missed that step in the setup document. Can you try running this on your raspberry pi:

pip install prometheus-client

Let me know the results and I can update the instructions!
